{{- if .Values.config.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prometheus-universal-exporter.fullname" . }}
  {{ with .Values.namespaceOverride }}namespace: {{ . }}{{ end }}
  labels:
    {{- include "prometheus-universal-exporter.metadataLabels" (list .) | nindent 4 }}
  annotations:
    {{- include "prometheus-universal-exporter.metadataAnnotations" (list .) | nindent 4 }}
data:
  {{- range $name, $content := .Values.config.data }}
  {{ $name }}: |
{{ $content | indent 4 }}
  {{- end }}
  {{- if .Values.staticTargets.enabled }}
  {{ include "prometheus-universal-exporter.staticTargetsFile" . }}: |
{{ .Values.staticTargets.data | indent 4 }}
  {{- end }}
{{- end }}
