{{- if and .Values.monitor.enabled (eq .Values.monitor.type "pod") }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "prometheus-universal-exporter.fullname" . }}
  {{ with .Values.namespaceOverride }}namespace: {{ . }}{{ end }}
  labels:
    {{- include "prometheus-universal-exporter.labels" . | nindent 4 }}
    {{- with .Values.monitor.labels }}{{ toYaml . | nindent 4 }}{{ end }}
  {{- with .Values.monitor.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    {{- if .Values.monitor.targetSelector }}{{ toYaml .Values.monitor.targetSelector | nindent 4 }}{{ else }}matchLabels:
      app.kubernetes.io/name: target
    {{- end }}
  podMetricsEndpoints:
    - port: http
      path: /probe
      interval: {{ .Values.monitor.interval }}
      scrapeTimeout: {{ .Values.monitor.scrapeTimeout }}
      params:
        collector: [{{ .Values.monitor.collector | quote }}]
        {{ range $name, $value := .Values.monitor.headers }}
        header_{{ $name }}: [{{ $value | quote }}]
        {{ end }}
      {{ if and .Values.monitor.auth.enabled (eq .Values.monitor.auth.type "bearer") }}
      authorization:
        type: Bearer
        credentials:
          name: {{ .Values.monitor.auth.secretName | quote }}
          key: {{ .Values.monitor.auth.secretKey | quote }}
          optional: {{ .Values.monitor.auth.optional }}
      {{ else if and .Values.monitor.auth.enabled (eq .Values.monitor.auth.type "basic") }}
      basicAuth:
        username:
          name: {{ .Values.monitor.auth.secretName | quote }}
          key: {{ .Values.monitor.auth.usernameKey | quote }}
          optional: {{ .Values.monitor.auth.optional }}
        password:
          name: {{ .Values.monitor.auth.secretName | quote }}
          key: {{ .Values.monitor.auth.passwordKey | quote }}
          optional: {{ .Values.monitor.auth.optional }}
      {{ end }}
      relabelings:
        - sourceLabels: [__address__]
          targetLabel: __param_target
        - sourceLabels: [__param_target]
          targetLabel: instance
        - targetLabel: __address__
          replacement: {{ include "prometheus-universal-exporter.fullname" . }}:{{ .Values.service.port }}
      {{- with .Values.monitor.relabelings }}
      {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.monitor.metricRelabelings }}
      metricRelabelings:
        {{ toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
{{- if and .Values.monitor.enabled (eq .Values.monitor.type "pod") .Values.selfMetrics.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "prometheus-universal-exporter.fullname" . }}-self
  {{ with .Values.namespaceOverride }}namespace: {{ . }}{{ end }}
  labels:
    {{- include "prometheus-universal-exporter.labels" . | nindent 4 }}
    {{- with .Values.selfMetrics.labels }}{{ toYaml . | nindent 4 }}{{ end }}
  {{- with .Values.selfMetrics.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "prometheus-universal-exporter.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  podMetricsEndpoints:
    - port: http
      path: {{ .Values.selfMetrics.path | quote }}
      interval: {{ .Values.selfMetrics.interval }}
      scrapeTimeout: {{ .Values.selfMetrics.scrapeTimeout }}
      {{- with .Values.selfMetrics.relabelings }}
      relabelings:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.selfMetrics.metricRelabelings }}
      metricRelabelings:
        {{ toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
