{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "prometheus-universal-exporter.serviceAccountName" . }}
  {{ with .Values.namespaceOverride }}namespace: {{ . }}{{ end }}
  labels:
    {{- include "prometheus-universal-exporter.metadataLabels" (list .) | nindent 4 }}
  annotations:
    {{- $annotations := .Values.serviceAccount.annotations | default dict -}}
    {{- include "prometheus-universal-exporter.metadataAnnotations" (list . $annotations) | nindent 4 }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
