package repository

import (
	"encoding/base64"
	"os"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
	"testing"

	"gopkg.in/yaml.v3"
)

// exampleCollectors is a config.yaml the chart's own checks accept.
const exampleCollectors = "collectors:\n  - name: example\n    request: {type: http}\n    transform: {type: regex}\n    metrics:\n      - name: v\n        expression: 'v=(\\d+)'\n"

// setFiles returns the helm arguments that give each file to the chart as
// --set-file does, under the values key prefix: byte for byte, which a values
// file cannot do for every content.
func setFiles(t *testing.T, prefix string, files map[string]string) []string {
	t.Helper()
	dir := t.TempDir()
	var args []string
	index := 0
	for name, content := range files {
		path := filepath.Join(dir, strconv.Itoa(index))
		index++
		if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
			t.Fatal(err)
		}
		args = append(args, "--set-file", prefix+strings.ReplaceAll(name, ".", `\.`)+"="+path)
	}
	return args
}

// configMapFiles renders the chart with args and returns the files of its
// ConfigMap as the pod would see them, with whether each was rendered as
// readable text under data rather than as base64 under binaryData. A key that
// is not a string, as an unquoted 123 or true would be, fails the test.
func configMapFiles(t *testing.T, helm string, args ...string) (files map[string]string, text map[string]bool) {
	t.Helper()
	files, text = map[string]string{}, map[string]bool{}
	for _, doc := range renderedDocuments(t, helm, args...) {
		if child(doc, "kind").Value != "ConfigMap" {
			continue
		}
		for _, section := range []string{"data", "binaryData"} {
			entries := child(doc, section)
			if entries == nil || entries.Kind != yaml.MappingNode {
				continue
			}
			for i := 0; i+1 < len(entries.Content); i += 2 {
				key, value := entries.Content[i], entries.Content[i+1]
				if key.Tag != "!!str" || value.Tag != "!!str" {
					t.Errorf("%s: the entry %q is a %s holding a %s, not a string holding a string", section, key.Value, key.Tag, value.Tag)
				}
				content := value.Value
				if section == "binaryData" {
					decoded, err := base64.StdEncoding.DecodeString(content)
					if err != nil {
						t.Fatalf("binaryData %q is not base64: %v", key.Value, err)
					}
					content = string(decoded)
				}
				if _, twice := files[key.Value]; twice {
					t.Errorf("%q is rendered twice", key.Value)
				}
				files[key.Value], text[key.Value] = content, section == "data"
			}
		}
	}
	return files, text
}

// Every file of the configuration reaches the pod as it was given. A block
// scalar without an indentation indicator takes its indentation from its
// first line, so a file whose first line was indented, as one starting with
// an indented comment is, ended the scalar at its first line indented less
// and rendering failed with a YAML error that named neither the file nor the
// cause; and a file name YAML reads as a number or a boolean was no string
// key. Ordinary files stay readable text in the ConfigMap; what a block
// scalar cannot hold unchanged is rendered under binaryData, the same file
// in the pod. Each text file is also rendered as the ConfigMap's last, where
// nothing follows to end its scalar, and as the static target document.
func TestChartRendersConfigurationFilesAsGiven(t *testing.T) {
	helm := requireHelm(t)
	files := map[string]struct {
		content string
		text    bool
	}{
		"indented-first-line.yaml":  {"  # generated by a tool\ncollectors: []\n", true},
		"blank-first-lines.yaml":    {"\n\ncollectors: []\n", true},
		"tab-first.yaml":            {"\tkey: value\n", true},
		"no-final-newline.yaml":     {"collectors: []", true},
		"document-markers.yaml":     {"---\n# comment\ncollectors: []\n...\n", true},
		"inner-blank-lines.yaml":    {"a: 1\n\n   \nb: 'x  '  \nc: 3\n", true},
		"not-ascii.yaml":            {"name: caf\u00e9 \u4e2d\u6587 \U0001f600\n", true},
		"123":                       {"a file named like a number\n", true},
		"true":                      {"a file named like a boolean\n", true},
		"two-final-newlines.yaml":   {"collectors: []\n\n", false},
		"final-trailing-space.yaml": {"collectors: [] \n", false},
		"final-space-line.yaml":     {"collectors: []\n  ", false},
		"final-no-break-space.yaml": {"name: caf\u00e9\u00a0\n", false},
		"carriage-returns.yaml":     {"a: 1\r\nb: 2\r\n", false},
		"control-character.yaml":    {"colour: \"\x1b[0m\"\n", false},
		"delete-character.yaml":     {"a\x7fb\n", false},
		"byte-order-mark.yaml":      {"\ufeffcollectors: []\n", false},
		"next-line.yaml":            {"a: 1\u0085b: 2\n", false},
		"line-separator.yaml":       {"a\u2028b\u2029c\n", false},
		"not-utf8.bin":              {"\xff\xfe\x00binary\n", false},
		"only-a-newline.yaml":       {"\n", false},
		"empty.yaml":                {"", false},
	}
	data := map[string]string{"config.yaml": exampleCollectors}
	for name, file := range files {
		data[name] = file.content
	}
	got, text := configMapFiles(t, helm, setFiles(t, "config.data.", data)...)
	if got["config.yaml"] != exampleCollectors || !text["config.yaml"] {
		t.Errorf("config.yaml is rendered as %q (text %v)", got["config.yaml"], text["config.yaml"])
	}
	for name, file := range files {
		if content, rendered := got[name]; !rendered || content != file.content {
			t.Errorf("%s: rendered %q (present %v), want %q", name, content, rendered, file.content)
		}
		if text[name] != file.text {
			t.Errorf("%s: rendered as text %v, want %v", name, text[name], file.text)
		}
	}
	if len(got) != len(files)+1 {
		t.Errorf("%d files rendered, want %d", len(got), len(files)+1)
	}

	// A block scalar that nothing follows, or that the static target file's
	// key follows, must still end where the file does.
	for name, file := range files {
		if !file.text {
			continue
		}
		t.Run("last and as static targets/"+name, func(t *testing.T) {
			args := setFiles(t, "config.data.", map[string]string{"config.yaml": exampleCollectors, "zzz-last": file.content})
			// The static target document must hold targets for the chart to
			// take it, so the file is its first lines.
			targets := file.content + "\ntargets:\n  - name: a\n    collector: example\n    target: http://a.example\n"
			args = append(args, setFiles(t, "staticTargets.", map[string]string{"data": targets})...)
			args = append(args, "--set", "staticTargets.enabled=true", "--set", "staticTargets.fileName=zzzz-static-targets", "--set", "staticTargets.monitor.enabled=false")
			got, text := configMapFiles(t, helm, args...)
			if got["zzz-last"] != file.content || !text["zzz-last"] {
				t.Errorf("as the last file of config.data: rendered %q (text %v), want %q", got["zzz-last"], text["zzz-last"], file.content)
			}
			if got["zzzz-static-targets"] != targets || !text["zzzz-static-targets"] {
				t.Errorf("as the static target document: rendered %q (text %v), want %q", got["zzzz-static-targets"], text["zzzz-static-targets"], targets)
			}
			// And with no static target file after it: the ConfigMap's last line.
			got, text = configMapFiles(t, helm, setFiles(t, "config.data.", map[string]string{"config.yaml": exampleCollectors, "zzz-last": file.content})...)
			if got["zzz-last"] != file.content || !text["zzz-last"] {
				t.Errorf("as the ConfigMap's last file: rendered %q (text %v), want %q", got["zzz-last"], text["zzz-last"], file.content)
			}
		})
	}
}

// The file `make helm-test` and CI give the chart as another file of
// config.data is there for its shape: a first line that is indented and a
// later line that is not, which is what ended a block scalar without an
// indentation indicator. An editor or a formatter that tidies it would leave
// those checks passing on a file that shows nothing, so the shape is held
// here, with the line the checks look for, and with helm the file is rendered
// and read back as it is.
func TestTheIndentedFileOfTheHelmChecksStaysIndentedAndRendersAsGiven(t *testing.T) {
	const path = "testdata/chart/indented-first-line.yaml"
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	content := string(raw)
	lines := strings.Split(strings.TrimSuffix(content, "\n"), "\n")
	if !strings.HasPrefix(lines[0], "  # A file whose first line is indented") {
		t.Errorf("%s starts with %q, not with the indented line the helm checks look for", path, lines[0])
	}
	flush := false
	for _, line := range lines[1:] {
		flush = flush || (line != "" && !strings.HasPrefix(line, " "))
	}
	if !flush {
		t.Errorf("%s has no line indented less than its first, which is what ended the block scalar:\n%s", path, content)
	}
	var document map[string]any
	if err := yaml.Unmarshal(raw, &document); err != nil {
		t.Errorf("%s is not YAML: %v", path, err)
	}

	helm := requireHelm(t)
	got, text := configMapFiles(t, helm, "--set-file", `config.data.extra\.yaml=`+path)
	if got["extra.yaml"] != content || !text["extra.yaml"] {
		t.Errorf("rendered %q (text %v), want the file as it is:\n%s", got["extra.yaml"], text["extra.yaml"], content)
	}
	if _, kept := got["config.yaml"]; !kept {
		t.Errorf("config.yaml is not rendered beside the file: %v", got)
	}
}

// The pods roll when any file of the configuration changes, whichever way
// the file is rendered: the checksum annotation follows config.yaml, a
// collector file, a file rendered under binaryData, a file's name and the
// static target document.
func TestChartChecksumFollowsEveryConfigurationFile(t *testing.T) {
	helm := requireHelm(t)
	checksum := func(data map[string]string, targets string) string {
		args := append(setFiles(t, "config.data.", data), "--show-only", "templates/deployment.yaml")
		if targets != "" {
			args = append(args, setFiles(t, "staticTargets.", map[string]string{"data": targets})...)
			args = append(args, "--set", "staticTargets.enabled=true", "--set", "staticTargets.monitor.enabled=false")
		}
		out, ok := helmTemplate(t, helm, chartDir, args...)
		if !ok {
			t.Fatalf("rendering failed:\n%s", out)
		}
		match := regexp.MustCompile(`checksum/config: ([0-9a-f]{64})\n`).FindStringSubmatch(out)
		if match == nil {
			t.Fatalf("the pod template has no checksum/config annotation:\n%s", out)
		}
		return match[1]
	}
	const targets = "targets:\n  - name: a\n    collector: example\n    target: http://a.example\n"
	base := map[string]string{"config.yaml": exampleCollectors, "collectors-a.yaml": "collectors: []\n", "windows.yaml": "collectors: []\r\n"}
	if first, second := checksum(base, ""), checksum(base, ""); first != second {
		t.Fatalf("the same values render two checksums, %s and %s", first, second)
	}
	seen := map[string]string{checksum(base, ""): "the base"}
	for name, change := range map[string]struct {
		file, content, targets string
	}{
		"config.yaml changed":                {file: "config.yaml", content: exampleCollectors + "# changed\n"},
		"a collector file changed":           {file: "collectors-a.yaml", content: "collectors: []\n# changed\n"},
		"a collector file's first line":      {file: "collectors-a.yaml", content: "  # indented\ncollectors: []\n"},
		"a file under binaryData changed":    {file: "windows.yaml", content: "collectors: []\r\n# changed\r\n"},
		"a file's final newline removed":     {file: "collectors-a.yaml", content: "collectors: []"},
		"a file added":                       {file: "collectors-b.yaml", content: "collectors: []\n"},
		"static targets added":               {targets: targets},
		"the static target document changed": {targets: targets + "# changed\n"},
	} {
		data := map[string]string{}
		for file, content := range base {
			data[file] = content
		}
		if change.file != "" {
			data[change.file] = change.content
		}
		sum := checksum(data, change.targets)
		if other, taken := seen[sum]; taken {
			t.Errorf("%s: the checksum is that of %s, so the pods would not roll", name, other)
		}
		seen[sum] = name
	}
}
